---
title: "Available Colors"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{available_colors}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

### Background (from OHA Style Guide)
The [USAID Graphics Standard Manual](https://www.usaid.gov/branding/gsm) lays out the two colors found in the agency’s logo as the primary color palette, USAID Blue and USAID Red. These colors are used to “reinforce that the aid is From the American people” but provide a limited range of colors to work with for data visualization.

OHA has developed an offshoot of these colors for visualization, expanding the number of categorical colors to choose from and creating a color-blind friendly palette (508 compliant). 

Strategic use of the OHA palette allows for consistent branding and reduces the time needed to think through color choices in every visualization. That said, colors should be used meaningfully and thought should be given to how these standard colors accentuate the visual/message.

Use USAID colors and text for all banners, text and text boxes. The USAID colors are available for use in graphs and charts, however the OHA palette is specifically for use in data visualization products (charts, graphs, visuals etc.). If in doubt of what color to use, try creating a visualization in black and white first. Then, add colors one at a time until data are sufficiently encoded to reinforce the message.

## Standalone Colors

### OHA Palette from OHA Style Guide
- midnight_blue <span style="background-color:#15478A">#15478A</span>
- viking <span style="background-color:#5BB5D5">#5BB5D5</span>
- slate <span style="background-color:#8C8C91">#8C8C91</span>
- orchid_bloom <span style="background-color:#E14BA1">#E14BA1</span>
- electric_indigo <span style="background-color:#3B5BBE">#3B5BBE</span>
- sun_kissed <span style="background-color:#F9C555">#F9C555</span>
- hunter <span style="background-color:#419164">#419164</span>
- lavender_haze <span style="background-color:#876EC4">#876EC4</span>
- tango <span style="background-color:#F36428">#F36428</span>

#### OHA Classic Colors 
- denim: <span style="background-color:#2057a7">#2057a7</span>
- old_rose: <span style="background-color:#c43d4d">#c43d4d</span>
- moody_blue: <span style="background-color:#8980cb">#8980cb</span>
- burnt_sienna: <span style="background-color:#e07653">#e07653</span>
- scooter: <span style="background-color:#1e87a5">#1e87a5</span>
- golden_sand: <span style="background-color:#f2bc40">#f2bc40</span>
- genoa: <span style="background-color:#287c6f">#287c6f</span>
- trolley_grey: <span style="background-color:#808080">#808080</span>

#### OHA Classic Light Colors
- denim_light: <span style="background-color:#bfddff">#bfddff</span>
- old_rose_light: <span style="background-color:#ff939a">#ff939a</span>
- moody_blue_light: <span style="background-color:#dfd3ff">#dfd3ff</span>
- burnt_sienna_light: <span style="background-color:#ffcaa2">#ffcaa2</span>
- scooter_med: <span style="background-color:#5BB5D5">#5BB5D5</span>
- scooter_light: <span style="background-color:#83dbfb">#83dbfb</span>
- golden_sand_light: <span style="background-color:#ffdda2">#ffdda2</span>
- genoa_light: <span style="background-color:#7ecfc0">#7ecfc0</span>
- trolley_grey_light: <span style="background-color:#e6e6e6">#e6e6e6</span>

#### OHA Grays from OHA Style Guide
- nero: <span style="background-color:#202020">#202020</span>
- matterhorn: <span style="background-color:#505050">#505050</span>
- suva_grey: <span style="background-color:#909090">#909090</span>
- whisper: <span style="background-color:#ebebeb">#ebebeb</span>
- light_grey: <span style="background-color:#d3d3d3">#d3d3d3</span>

#### Standard USAID colors from USAID Style Guide
- usaid_blue: <span style="background-color:#002a6c">#002a6c</span>
- usaid_red: <span style="background-color:#ba0c2f">#ba0c2f</span>
- usaid_black: <span style="background-color:#212721">#212721</span>
- usaid_medblue: <span style="background-color:#0067b9">#0067b9</span>
- usaid_lightblue: <span style="background-color:#a7c6ed">#a7c6ed</span>
- usaid_darkgrey: <span style="background-color:#6c6463">#6c6463</span>
- usaid_medgrey: <span style="background-color:#8C8985">#8C8985</span>
- usaid_lightgrey: <span style="background-color:#cfcdc9">#cfcdc9</span>

#### Gray Palette from Laura D. Hughes who was inspired by Adobe #grays
- grey10k: <span style="background-color:#E6E7E8">#E6E7E8</span>
- grey20k: <span style="background-color:#d1d3d4">#d1d3d4</span>
- grey30k: <span style="background-color:#BCBEC0">#BCBEC0</span>
- grey40k: <span style="background-color:#a7a9ac">#a7a9ac</span>
- grey50k: <span style="background-color:#939598">#939598</span>
- grey60k: <span style="background-color:#808080">#808080</span>
- grey70k: <span style="background-color:#6d6e71">#6d6e71</span>
- grey80k: <span style="background-color:#58595b">#58595b</span>
- grey90k: <span style="background-color:#414042">#414042</span>

#### Pantone Color of the Year (2000-2024)
- pantone_cerulean: <span style="background-color:#9BB7D4">#9BB7D4</span>
- pantone_fuchsia_rose: <span style="background-color:#C74375">#C74375</span>
- pantone_true_red: <span style="background-color:#BF1932">#BF1932</span>
- pantone_aqua_sky: <span style="background-color:#7BC4C4">#7BC4C4</span>
- pantone_tigerlily: <span style="background-color:#E2583E">#E2583E</span>
- pantone_blue_turquoise: <span style="background-color:#53B0AE">#53B0AE</span>
- pantone_sand_dollar: <span style="background-color:#DECDBE">#DECDBE</span>
- pantone_chili_pepper: <span style="background-color:#9B1B30">#9B1B30</span>
- pantone_blue_iris: <span style="background-color:#5A5B9F">#5A5B9F</span>
- pantone_mimosa: <span style="background-color:#F0C05A">#F0C05A</span>
- pantone_honeysuckle : <span style="background-color:#D94F70">#D94F70</span>
- pantone_turquoise : <span style="background-color:#45B5AA">#45B5AA</span>
- pantone_tangerine_tango: <span style="background-color:#DD4124">#DD4124</span>
- pantone_emerald: <span style="background-color:#009473">#009473</span>
- pantone_radiant_orchid: <span style="background-color:#AD5E99">#AD5E99</span>
- pantone_marsala: <span style="background-color:#964F4C">#964F4C</span>
- pantone_serenity: <span style="background-color:#93A9D1">#93A9D1</span>
- pantone_rose_quartz: <span style="background-color:#F7CACA">#F7CACA</span>
- pantone_greenery: <span style="background-color:#88B04B">#88B04B</span>
- pantone_ultra_violet: <span style="background-color:#5F4B8B">#5F4B8B</span>
- pantone_living_coral: <span style="background-color:#FF6F61">#FF6F61</span>
- pantone_classic_blue: <span style="background-color:#0F4C81">#0F4C81</span>
- pantone_ultimate_gray: <span style="background-color:#939597">#939597</span>
- pantone_illuminating: <span style="background-color:#F5DF4D">#F5DF4D</span>
- pantone_very_peri: <span style="background-color:#6768AB">#6768AB</span>
- pantone_viva_magenta: <span style="background-color:#BE3455">#BE3455</span>
- pantone_peach_fuzz: <span style="background-color:#FEBE98">#FEBE98</span>

#### Washington Post Inspired colors
- wapo_lpurple: <span style="background-color:#C7ABC7">#C7ABC7</span>
- wapo_lorange: <span style="background-color:#F4AB67">#F4AB67</span>
- wapo_pushpop: <span style="background-color:#FEC693">#FEC693</span>
- wapo_lgreen: <span style="background-color:#B5D1D0">#B5D1D0</span>
- wapo_lorange2: <span style="background-color:#EFCAB4">#EFCAB4</span>
- wapo_dorange: <span style="background-color:#DC7C33">#DC7C33</span>
- wapo_lblue: <span style="background-color:#B4D5E5">#B4D5E5</span>
- wapo_dblue: <span style="background-color:#3579A8">#3579A8</span>
- wapo_lmauve: <span style="background-color:#D8B3D4">#D8B3D4</span>
- wapo_dmauve: <span style="background-color:#B68AB8">#B68AB8</span>

## Palettes 

#### OHA
- siei:  <span style="background-color:#2057a7">#2057a7</span>  <span style="background-color:#c43d4d">#c43d4d</span>  <span style="background-color:#8980cb">#8980cb</span>  <span style="background-color:#e07653">#e07653</span>  <span style="background-color:#1e87a5">#1e87a5</span>  <span style="background-color:#f2bc40">#f2bc40</span>  <span style="background-color:#287c6f">#287c6f</span>  <span style="background-color:#808080">#808080</span> 
- siei_pairs:  <span style="background-color:#2057a7">#2057a7</span>  <span style="background-color:#BFDDFF">#BFDDFF</span>  <span style="background-color:#c43d4d">#c43d4d</span>  <span style="background-color:#FF939A">#FF939A</span>  <span style="background-color:#8980cb">#8980cb</span>  <span style="background-color:#DFD3FF">#DFD3FF</span>  <span style="background-color:#e07653">#e07653</span>  <span style="background-color:#FFCAA2">#FFCAA2</span>  <span style="background-color:#1e87a5">#1e87a5</span>  <span style="background-color:#83DBFB">#83DBFB</span>  <span style="background-color:#f2bc40">#f2bc40</span>  <span style="background-color:#FFDDA2">#FFDDA2</span>  <span style="background-color:#287c6f">#287c6f</span>  <span style="background-color:#7ECFC0">#7ECFC0</span>  <span style="background-color:#808080">#808080</span>  <span style="background-color:#E6E6E6">#E6E6E6</span> 
- siei_achv:  <span style="background-color:#FF939A">#FF939A</span>  <span style="background-color:#FFCAA2">#FFCAA2</span>  <span style="background-color:#5BB5D5">#5BB5D5</span>  <span style="background-color:#E6E6E6">#E6E6E6</span> 

#### OHA Discrete Primary + Ordered
- denim:  <span style="background-color:#2057a7">#2057a7</span>  <span style="background-color:#1e87a5">#1e87a5</span>  <span style="background-color:#e07653">#e07653</span>  <span style="background-color:#f2bc40">#f2bc40</span>  <span style="background-color:#8980cb">#8980cb</span> 
- old_rose:  <span style="background-color:#c43d4d">#c43d4d</span>  <span style="background-color:#1e87a5">#1e87a5</span>  <span style="background-color:#8980cb">#8980cb</span>  <span style="background-color:#e07653">#e07653</span>  <span style="background-color:#287c6f">#287c6f</span> 
- moody_blue:  <span style="background-color:#8980cb">#8980cb</span>  <span style="background-color:#287c6f">#287c6f</span>  <span style="background-color:#2057a7">#2057a7</span>  <span style="background-color:#e07653">#e07653</span>  <span style="background-color:#1e87a5">#1e87a5</span> 
- burnt_sienna:  <span style="background-color:#e07653">#e07653</span>  <span style="background-color:#8980cb">#8980cb</span>  <span style="background-color:#f2bc40">#f2bc40</span>  <span style="background-color:#c43d4d">#c43d4d</span>  <span style="background-color:#1e87a5">#1e87a5</span> 
- scooter:  <span style="background-color:#1e87a5">#1e87a5</span>  <span style="background-color:#c43d4d">#c43d4d</span>  <span style="background-color:#8980cb">#8980cb</span>  <span style="background-color:#f2bc40">#f2bc40</span>  <span style="background-color:#287c6f">#287c6f</span> 
- golden_sand:  <span style="background-color:#f2bc40">#f2bc40</span>  <span style="background-color:#2057a7">#2057a7</span>  <span style="background-color:#287c6f">#287c6f</span>  <span style="background-color:#e07653">#e07653</span>  <span style="background-color:#8980cb">#8980cb</span> 
- genoa:  <span style="background-color:#287c6f">#287c6f</span>  <span style="background-color:#8980cb">#8980cb</span>  <span style="background-color:#f2bc40">#f2bc40</span>  <span style="background-color:#e07653">#e07653</span>  <span style="background-color:#1e87a5">#1e87a5</span> 

#### OHA Continuous Primary
- denims:  <span style="background-color:#bfddff">#bfddff</span>  <span style="background-color:#a5c5ff">#a5c5ff</span>  <span style="background-color:#8badfe">#8badfe</span>  <span style="background-color:#7396ee">#7396ee</span>  <span style="background-color:#5b82d8">#5b82d8</span>  <span style="background-color:#436ec1">#436ec1</span>  <span style="background-color:#265bab">#265bab</span>  <span style="background-color:#074895">#074895</span>  <span style="background-color:#00347d">#00347d</span>  <span style="background-color:#002065">#002065</span>  <span style="background-color:#000c4f">#000c4f</span> 
- old_roses:  <span style="background-color:#ffb5ba">#ffb5ba</span>  <span style="background-color:#ff989f">#ff989f</span>  <span style="background-color:#fc7a83">#fc7a83</span>  <span style="background-color:#ee636e">#ee636e</span>  <span style="background-color:#d8505d">#d8505d</span>  <span style="background-color:#c33c4c">#c33c4c</span>  <span style="background-color:#af273d">#af273d</span>  <span style="background-color:#990d2e">#990d2e</span>  <span style="background-color:#7f001c">#7f001c</span>  <span style="background-color:#630005">#630005</span>  <span style="background-color:#480000">#480000</span> 
- moody_blues:  <span style="background-color:#e9ddff">#e9ddff</span>  <span style="background-color:#cfc3ff">#cfc3ff</span>  <span style="background-color:#b5aaf9">#b5aaf9</span>  <span style="background-color:#9e94e0">#9e94e0</span>  <span style="background-color:#877ec9">#877ec9</span>  <span style="background-color:#7069b2">#7069b2</span>  <span style="background-color:#5a559b">#5a559b</span>  <span style="background-color:#454185">#454185</span>  <span style="background-color:#2f2e6f">#2f2e6f</span>  <span style="background-color:#171d5a">#171d5a</span>  <span style="background-color:#000a45">#000a45</span> 
- burnt_siennas:  <span style="background-color:#ffd4ac">#ffd4ac</span>  <span style="background-color:#ffb790">#ffb790</span>  <span style="background-color:#fd9873">#fd9873</span>  <span style="background-color:#ec815d">#ec815d</span>  <span style="background-color:#d56d4b">#d56d4b</span>  <span style="background-color:#bf5a39">#bf5a39</span>  <span style="background-color:#a84728">#a84728</span>  <span style="background-color:#923417">#923417</span>  <span style="background-color:#7c2105">#7c2105</span>  <span style="background-color:#670901">#670901</span>  <span style="background-color:#4c0000">#4c0000</span> 
- scooters:  <span style="background-color:#a6fdff">#a6fdff</span>  <span style="background-color:#8ce4fe">#8ce4fe</span>  <span style="background-color:#74ccec">#74ccec</span>  <span style="background-color:#5bb5d5">#5bb5d5</span>  <span style="background-color:#419fbe">#419fbe</span>  <span style="background-color:#228aa8">#228aa8</span>  <span style="background-color:#047491">#047491</span>  <span style="background-color:#005e7a">#005e7a</span>  <span style="background-color:#004964">#004964</span>  <span style="background-color:#00354f">#00354f</span>  <span style="background-color:#00223a">#00223a</span> 
- golden_sands:  <span style="background-color:#ffec6f">#ffec6f</span>  <span style="background-color:#fcce52">#fcce52</span>  <span style="background-color:#eab538">#eab538</span>  <span style="background-color:#d2a01e">#d2a01e</span>  <span style="background-color:#ba8b00">#ba8b00</span>  <span style="background-color:#a27600">#a27600</span>  <span style="background-color:#8a6200">#8a6200</span>  <span style="background-color:#734f00">#734f00</span>  <span style="background-color:#5e3c00">#5e3c00</span>  <span style="background-color:#4b2900">#4b2900</span>  <span style="background-color:#3b1500">#3b1500</span> 
- genoas:  <span style="background-color:#a0f2e2">#a0f2e2</span>  <span style="background-color:#89dacb">#89dacb</span>  <span style="background-color:#72c3b4">#72c3b4</span>  <span style="background-color:#5cac9e">#5cac9e</span>  <span style="background-color:#459688">#459688</span>  <span style="background-color:#2d8073">#2d8073</span>  <span style="background-color:#0d6c5f">#0d6c5f</span>  <span style="background-color:#01564b">#01564b</span>  <span style="background-color:#004137">#004137</span>  <span style="background-color:#002e24">#002e24</span>  <span style="background-color:#001b0e">#001b0e</span> 
- trolley_greys:  <span style="background-color:#E6E7E8">#E6E7E8</span>  <span style="background-color:#D5D7D8">#D5D7D8</span>  <span style="background-color:#C4C6C8">#C4C6C8</span>  <span style="background-color:#B3B5B8">#B3B5B8</span>  <span style="background-color:#A3A4A8">#A3A4A8</span>  <span style="background-color:#939598">#939598</span>  <span style="background-color:#838484">#838484</span>  <span style="background-color:#747576">#747576</span>  <span style="background-color:#646568">#646568</span>  <span style="background-color:#535356">#535356</span>  <span style="background-color:#414042">#414042</span> 

#### USAID
- usaid_colors:  <span style="background-color:#002a6c">#002a6c</span>  <span style="background-color:#ba0c2f">#ba0c2f</span>  <span style="background-color:#212721">#212721</span>  <span style="background-color:#0067b9">#0067b9</span>  <span style="background-color:#a7c6ed">#a7c6ed</span>  <span style="background-color:#6c6463">#6c6463</span>  <span style="background-color:#8C8985">#8C8985</span>  <span style="background-color:#cfcdc9">#cfcdc9</span> 

#### Cartodb Colors
- carto_burgyl:  <span style="background-color:#fbe6c5">#fbe6c5</span>  <span style="background-color:#f5ba98">#f5ba98</span>  <span style="background-color:#ee8a82">#ee8a82</span>  <span style="background-color:#dc7176">#dc7176</span>  <span style="background-color:#c8586c">#c8586c</span>  <span style="background-color:#9c3f5d">#9c3f5d</span>  <span style="background-color:#70284a">#70284a</span> 
- carto_sunset:  <span style="background-color:#fcde9c">#fcde9c</span>  <span style="background-color:#faa476">#faa476</span>  <span style="background-color:#f0746e">#f0746e</span>  <span style="background-color:#e34f6f">#e34f6f</span>  <span style="background-color:#dc3977">#dc3977</span>  <span style="background-color:#b9257a">#b9257a</span>  <span style="background-color:#7c1d6f">#7c1d6f</span> 
- carto_teal:  <span style="background-color:#d1eeea">#d1eeea</span>  <span style="background-color:#a8dbd9">#a8dbd9</span>  <span style="background-color:#85c4c9">#85c4c9</span>  <span style="background-color:#68abb8">#68abb8</span>  <span style="background-color:#4f90a6">#4f90a6</span>  <span style="background-color:#3b738f">#3b738f</span>  <span style="background-color:#2a5674">#2a5674</span> 
- carto_dmint:  <span style="background-color:#d2fbd4">#d2fbd4</span>  <span style="background-color:#a5dbc2">#a5dbc2</span>  <span style="background-color:#7bbcb0">#7bbcb0</span>  <span style="background-color:#559c9e">#559c9e</span>  <span style="background-color:#3a7c89">#3a7c89</span>  <span style="background-color:#235d72">#235d72</span>  <span style="background-color:#123f5a">#123f5a</span> 
- carto_mint:  <span style="background-color:#e4f1e1">#e4f1e1</span>  <span style="background-color:#b4d9cc">#b4d9cc</span>  <span style="background-color:#89c0b6">#89c0b6</span>  <span style="background-color:#63a6a0">#63a6a0</span>  <span style="background-color:#448c8a">#448c8a</span>  <span style="background-color:#287274">#287274</span>  <span style="background-color:#0d585f">#0d585f</span> 
- carto_brown:  <span style="background-color:#ede5cf">#ede5cf</span>  <span style="background-color:#e0c2a2">#e0c2a2</span>  <span style="background-color:#d39c83">#d39c83</span>  <span style="background-color:#c1766f">#c1766f</span>  <span style="background-color:#a65461">#a65461</span>  <span style="background-color:#813753">#813753</span>  <span style="background-color:#541f3f">#541f3f</span> 

#### Carto Diverging
- carto_div_armyrose:  <span style="background-color:#798234">#798234</span>  <span style="background-color:#a3ad62">#a3ad62</span>  <span style="background-color:#d0d3a2">#d0d3a2</span>  <span style="background-color:#fdfbe4">#fdfbe4</span>  <span style="background-color:#f0c6c3">#f0c6c3</span>  <span style="background-color:#df91a3">#df91a3</span>  <span style="background-color:#d46780">#d46780</span> 
- carto_div_fall:  <span style="background-color:#3d5941">#3d5941</span>  <span style="background-color:#778868">#778868</span>  <span style="background-color:#b5b991">#b5b991</span>  <span style="background-color:#f6edbd">#f6edbd</span>  <span style="background-color:#edbb8a">#edbb8a</span>  <span style="background-color:#de8a5a">#de8a5a</span>  <span style="background-color:#ca562c">#ca562c</span> 
- carto_div_geyser:  <span style="background-color:#008080">#008080</span>  <span style="background-color:#70a494">#70a494</span>  <span style="background-color:#b4c8a8">#b4c8a8</span>  <span style="background-color:#f6edbd">#f6edbd</span>  <span style="background-color:#edbb8a">#edbb8a</span>  <span style="background-color:#de8a5a">#de8a5a</span>  <span style="background-color:#ca562c">#ca562c</span> 
- carto_div_temps:  <span style="background-color:#009392">#009392</span>  <span style="background-color:#39b185">#39b185</span>  <span style="background-color:#9ccb86">#9ccb86</span>  <span style="background-color:#e9e29c">#e9e29c</span>  <span style="background-color:#eeb479">#eeb479</span>  <span style="background-color:#e88471">#e88471</span>  <span style="background-color:#cf597e">#cf597e</span> 
- carto_div_teal:  <span style="background-color:#009392">#009392</span>  <span style="background-color:#72aaa1">#72aaa1</span>  <span style="background-color:#b1c7b3">#b1c7b3</span>  <span style="background-color:#f1eac8">#f1eac8</span>  <span style="background-color:#e5b9ad">#e5b9ad</span>  <span style="background-color:#d98994">#d98994</span>  <span style="background-color:#d0587e">#d0587e</span> 
- carto_div_tropic:  <span style="background-color:#009B9E">#009B9E</span>  <span style="background-color:#42B7B9">#42B7B9</span>  <span style="background-color:#A7D3D4">#A7D3D4</span>  <span style="background-color:#F1F1F1">#F1F1F1</span>  <span style="background-color:#E4C1D9">#E4C1D9</span>  <span style="background-color:#D691C1">#D691C1</span>  <span style="background-color:#C75DAB">#C75DAB</span> 
- carto_div_earth:  <span style="background-color:#A16928">#A16928</span>  <span style="background-color:#bd925a">#bd925a</span>  <span style="background-color:#d6bd8d">#d6bd8d</span>  <span style="background-color:#edeac2">#edeac2</span>  <span style="background-color:#b5c8b8">#b5c8b8</span>  <span style="background-color:#79a7ac">#79a7ac</span>  <span style="background-color:#2887a1">#2887a1</span> 
  
#### Other
- pantone: <span style="background-color:#BE3455">#BE3455</span>  <span style="background-color:#6768AB">#6768AB</span>  <span style="background-color:#F5DF4D">#F5DF4D</span>  <span style="background-color:#939597">#939597</span>  <span style="background-color:#0F4C81">#0F4C81</span>  <span style="background-color:#FF6F61">#FF6F61</span>  <span style="background-color:#5F4B8B">#5F4B8B</span>  <span style="background-color:#88B04B">#88B04B</span>  <span style="background-color:#F7CACA">#F7CACA</span>  <span style="background-color:#93A9D1">#93A9D1</span>  <span style="background-color:#964F4C">#964F4C</span>  <span style="background-color:#AD5E99">#AD5E99</span>  <span style="background-color:#009473">#009473</span>  <span style="background-color:#DD4124">#DD4124</span>  <span style="background-color:#45B5AA">#45B5AA</span>  <span style="background-color:#D94F70">#D94F70</span>  <span style="background-color:#F0C05A">#F0C05A</span>  <span style="background-color:#5A5B9F">#5A5B9F</span>  <span style="background-color:#9B1B30">#9B1B30</span>  <span style="background-color:#DECDBE">#DECDBE</span>  <span style="background-color:#53B0AE">#53B0AE</span>  <span style="background-color:#E2583E">#E2583E</span>  <span style="background-color:#7BC4C4">#7BC4C4</span>  <span style="background-color:#BF1932">#BF1932</span>  <span style="background-color:#C74375">#C74375</span>  <span style="background-color:#9BB7D4">#9BB7D4</span>
- contrast:  <span style="background-color:#E4F4EA">#E4F4EA</span>  <span style="background-color:#364352">#364352</span>  <span style="background-color:#768491">#768491</span>  <span style="background-color:#C5CAD0">#C5CAD0</span>  <span style="background-color:#BE311F">#BE311F</span> 
- compliment:  <span style="background-color:#6F472E">#6F472E</span>  <span style="background-color:#6F827C">#6F827C</span>  <span style="background-color:#E4F4EA">#E4F4EA</span>  <span style="background-color:#E4F4EA">#E4F4EA</span>  <span style="background-color:#E4F4EA">#E4F4EA</span> 
- outbreak_or:  <span style="background-color:#F4E5D2">#F4E5D2</span>  <span style="background-color:#FED79C">#FED79C</span>  <span style="background-color:#FBA529">#FBA529</span>  <span style="background-color:#FF6600">#FF6600</span> 
- seablue:  <span style="background-color:#4FAFB6">#4FAFB6</span>  <span style="background-color:#98CBD0">#98CBD0</span>  <span style="background-color:#D5EAEB">#D5EAEB</span>  <span style="background-color:#086EA1">#086EA1</span> 
- seablue_text:  <span style="background-color:#00949D">#00949D</span>  <span style="background-color:#58B2BA">#58B2BA</span>  <span style="background-color:#B2D8DD">#B2D8DD</span>  <span style="background-color:#2476A6">#2476A6</span> 
- category10:  <span style="background-color:#1f77b4">#1f77b4</span>  <span style="background-color:#ff7f0e">#ff7f0e</span>  <span style="background-color:#2ca02c">#2ca02c</span>  <span style="background-color:#d62728">#d62728</span>  <span style="background-color:#9467bd">#9467bd</span>  <span style="background-color:#8c564b">#8c564b</span>  <span style="background-color:#e377c2">#e377c2</span>  <span style="background-color:#7f7f7f">#7f7f7f</span>  <span style="background-color:#bcbd22">#bcbd22</span>  <span style="background-color:#17becf">#17becf</span> 
- category20:  <span style="background-color:#1f77b4">#1f77b4</span>  <span style="background-color:#aec7e8">#aec7e8</span>  <span style="background-color:#ff7f0e">#ff7f0e</span>  <span style="background-color:#ffbb78">#ffbb78</span>  <span style="background-color:#2ca02c">#2ca02c</span>  <span style="background-color:#98df8a">#98df8a</span>  <span style="background-color:#d62728">#d62728</span>  <span style="background-color:#ff9896">#ff9896</span>  <span style="background-color:#9467bd">#9467bd</span>  <span style="background-color:#c5b0d5">#c5b0d5</span>  <span style="background-color:#8c564b">#8c564b</span>  <span style="background-color:#c49c94">#c49c94</span>  <span style="background-color:#e377c2">#e377c2</span>  <span style="background-color:#f7b6d2">#f7b6d2</span>  <span style="background-color:#7f7f7f">#7f7f7f</span>  <span style="background-color:#c7c7c7">#c7c7c7</span>  <span style="background-color:#bcbd22">#bcbd22</span>  <span style="background-color:#dbdb8d">#dbdb8d</span>  <span style="background-color:#17becf">#17becf</span>  <span style="background-color:#9edae5">#9edae5</span> 
- category20b:  <span style="background-color:#393b79">#393b79</span>  <span style="background-color:#5254a3">#5254a3</span>  <span style="background-color:#6b6ecf">#6b6ecf</span>  <span style="background-color:#9c9ede">#9c9ede</span>  <span style="background-color:#637939">#637939</span>  <span style="background-color:#8ca252">#8ca252</span>  <span style="background-color:#b5cf6b">#b5cf6b</span>  <span style="background-color:#cedb9c">#cedb9c</span>  <span style="background-color:#8c6d31">#8c6d31</span>  <span style="background-color:#bd9e39">#bd9e39</span>  <span style="background-color:#e7ba52">#e7ba52</span>  <span style="background-color:#e7cb94">#e7cb94</span>  <span style="background-color:#843c39">#843c39</span>  <span style="background-color:#ad494a">#ad494a</span>  <span style="background-color:#d6616b">#d6616b</span>  <span style="background-color:#e7969c">#e7969c</span>  <span style="background-color:#7b4173">#7b4173</span>  <span style="background-color:#a55194">#a55194</span>  <span style="background-color:#ce6dbd">#ce6dbd</span>  <span style="background-color:#de9ed6">#de9ed6</span> 
- category20c:  <span style="background-color:#3182bd">#3182bd</span>  <span style="background-color:#6baed6">#6baed6</span>  <span style="background-color:#9ecae1">#9ecae1</span>  <span style="background-color:#c6dbef">#c6dbef</span>  <span style="background-color:#e6550d">#e6550d</span>  <span style="background-color:#fd8d3c">#fd8d3c</span>  <span style="background-color:#fdae6b">#fdae6b</span>  <span style="background-color:#fdd0a2">#fdd0a2</span>  <span style="background-color:#31a354">#31a354</span>  <span style="background-color:#74c476">#74c476</span>  <span style="background-color:#a1d99b">#a1d99b</span>  <span style="background-color:#c7e9c0">#c7e9c0</span>  <span style="background-color:#756bb1">#756bb1</span>  <span style="background-color:#9e9ac8">#9e9ac8</span>  <span style="background-color:#bcbddc">#bcbddc</span>  <span style="background-color:#dadaeb">#dadaeb</span>  <span style="background-color:#636363">#636363</span>  <span style="background-color:#969696">#969696</span>  <span style="background-color:#bdbdbd">#bdbdbd</span>  <span style="background-color:#d9d9d9">#d9d9d9</span> 
                    
